# Stage 1: Builder
FROM node:22-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_API_SOURCE
ARG NEXT_PUBLIC_API_SOURCE_FINANCE
ARG NEXT_PUBLIC_API_SOURCE_PERPUS
ARG NEXT_PUBLIC_URL_PORTAL
ARG NEXT_PUBLIC_API_MOCKING

ENV NEXT_PUBLIC_API_SOURCE=${NEXT_PUBLIC_API_SOURCE}
ENV NEXT_PUBLIC_API_SOURCE_FINANCE=${NEXT_PUBLIC_API_SOURCE_FINANCE}
ENV NEXT_PUBLIC_API_SOURCE_PERPUS=${NEXT_PUBLIC_API_SOURCE_PERPUS}
ENV NEXT_PUBLIC_URL_PORTAL=${NEXT_PUBLIC_URL_PORTAL}
ENV NEXT_PUBLIC_API_MOCKING=${NEXT_PUBLIC_API_MOCKING}

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Buang semua devDependencies
RUN npm prune --omit=dev

# Stage 2: Runner (lightweight)
FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ARG NEXT_PUBLIC_API_SOURCE
ARG NEXT_PUBLIC_API_SOURCE_FINANCE
ARG NEXT_PUBLIC_API_SOURCE_PERPUS
ARG NEXT_PUBLIC_URL_PORTAL
ARG NEXT_PUBLIC_API_MOCKING
ENV NEXT_PUBLIC_API_SOURCE=${NEXT_PUBLIC_API_SOURCE}
ENV NEXT_PUBLIC_API_SOURCE_FINANCE=${NEXT_PUBLIC_API_SOURCE_FINANCE}
ENV NEXT_PUBLIC_API_SOURCE_PERPUS=${NEXT_PUBLIC_API_SOURCE_PERPUS}
ENV NEXT_PUBLIC_URL_PORTAL=${NEXT_PUBLIC_URL_PORTAL}
ENV NEXT_PUBLIC_API_MOCKING=${NEXT_PUBLIC_API_MOCKING}

# Copy only what's needed
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.js ./next.config.js

EXPOSE 3000

CMD ["npm", "start"]
